#!/bin/bash

# Справка по скриптам Airflow

echo "📚 Справка по скриптам Airflow"
echo "=============================="
echo ""
echo "🔧 Доступные скрипты:"
echo ""
echo "  ./start.sh          - Запуск Airflow"
echo "  ./stop.sh           - Остановка Airflow"
echo "  ./restart.sh        - Перезапуск Airflow"
echo "  ./cold-start.sh     - Холодный запуск с очисткой данных"
echo "  ./clean.sh          - Полная очистка (удаляет все данные)"
echo "  ./status.sh         - Проверка статуса сервисов"
echo "  ./logs.sh           - Просмотр логов (опционально: ./logs.sh [service_name])"
echo "  ./help.sh           - Эта справка"
echo ""
echo "🌐 Доступ:"
echo "  Webserver: http://localhost:8080"
echo "  Credentials: admin / admin"
echo ""
echo "📊 Основные команды docker-compose:"
echo "  docker-compose ps                 - Статус контейнеров"
echo "  docker-compose logs -f            - Логи всех сервисов"
echo "  docker-compose logs -f [service]  - Логи конкретного сервиса"
echo ""
echo "✅ Примеры использования:"
echo ""
echo "  # Первый запуск Airflow:"
echo "  ./cold-start.sh"
echo ""
echo "  # Остановить Airflow:"
echo "  ./stop.sh"
echo ""
echo "  # Просмотр логов scheduler'а:"
echo "  ./logs.sh airflow-scheduler"
echo ""
